spring:
  config.activate.on-profile: default
  web.resources.static-locations: file:./app/
cds:
  datasource:
    auto-config.enabled: false
  security.mock.users:
    - name: admin
      password: admin
      roles:
      - admin
      attributes:
        businessPartner:
        - "10401010"
    - name: user
      password: user